---
# Source: loki-stack/charts/loki/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: loki
    chart: loki-2.16.0
    release: loki-stack
    heritage: Helm
  annotations:
    {}
  name: loki-stack
  namespace: monitoring
automountServiceAccountToken: true
