apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.monitoring.svc.cluster.local:8080",
                "version": 1
            },
            {
               "access":"proxy",
                "editable": true,
                "name": "loki",
                "orgId": 1,
                "type": "loki",
                "url": "http://loki.monitoring.svc.cluster.local:3100",
                "version": 1
            },
            {
               "access":"proxy",
                "editable": true,
                "name": "alertmanager",
                "orgId": 1,
                "type": "loki",
                "url": "http://alertmanager.monitoring.svc.cluster.local:9093",
                "version": 1
            }
        ]
    }