apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
    group: grafana
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: promtail
    group: grafana
  name: promtail
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods  
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
  labels:
    app: promtail
    group: grafana
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: promtail
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
    group: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
      group: grafana
  template:
    metadata:
      labels:
        app: promtail
        group: grafana
    spec:
      containers:
        - name: promtail
          image: promtail/promtail:latest #grafana/promtail:make-images-static-26a87c9
          imagePullPolicy: Always
          args: ["-config.file=/etc/promtail/promtail-config.yaml"]
          volumeMounts:
          - name: promtail-config
            mountPath: /etc/promtail/
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
