---
# Source: loki-stack/charts/promtail/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-stack-promtail
  namespace: monitoring
  labels:
    helm.sh/chart: promtail-6.10.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: loki-stack
    app.kubernetes.io/version: "2.7.4"
    app.kubernetes.io/managed-by: Helm
