---
# Source: prometheus-blackbox-exporter/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: prometheus-blackbox-exporter-4.3.1
  name: release-name-prometheus-blackbox-exporter
  #namespace: monitoring
rules:
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    resourceNames:
    - release-name-prometheus-blackbox-exporter-psp
    verbs:
    - use
