---
# Source: prometheus-blackbox-exporter/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: prometheus-blackbox-exporter-4.3.1
  name: release-name-prometheus-blackbox-exporter
  #namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-prometheus-blackbox-exporter
subjects:
  - kind: ServiceAccount
    name: release-name-prometheus-blackbox-exporter
